### PR TITLE
Created PID Controller

### PR DESCRIPTION
**Pull request by rmcar17**
This can be used for things like compass correction. It has been setup on the current robot to compass correct.

### CODE REVIEW

**Comment by Coolkidgoodking** [comment]
does it actually work thou? can i have a video of it working : v)

**Comment by rmcar17** [comment]
It works, Josh saw it work.

**Comment by rmcar17** [comment]
I can show you in robotics this afternoon

**Comment by Coolkidgoodking** [comment]
k, i'll confirm the merge after i have seen it work. don't reply till then

**Comment by rmcar17** [comment]
k

**Pull request merged**
